import '../util.dart';

// Canned animations standing in for model output. Each obeys the same rules
// the real prompt imposes: one self-contained document, no network, loops,
// honours prefers-reduced-motion.

const _base = r'''
<!doctype html><html><head><meta charset="utf-8"><style>
*{box-sizing:border-box}html,body{margin:0;height:100%;background:#0b0b0f;color:#f5f5f7;
font:15px/1.4 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;overflow:hidden}
.stage{position:absolute;inset:0;display:grid;grid-template-rows:auto 1fr auto;padding:4vh 5vw}
h1{margin:0;font-size:clamp(18px,3.4vw,30px);letter-spacing:-.01em;font-weight:650}
.sub{color:#a1a1a6;font-size:clamp(12px,1.6vw,15px);margin-top:.35em}
.foot{color:#6e6e73;font-size:12px}
svg{width:100%;height:100%}
''';

String _doc(String title, String sub, String css, String body, String js) => '''
$_base$css</style></head><body><div class="stage">
<div><h1>${htmlEscape(title)}</h1><div class="sub">${htmlEscape(sub)}</div></div>
$body
<div class="foot">Generated by Zakerly from your course material</div></div>
<script>
const reduce = matchMedia('(prefers-reduced-motion: reduce)').matches;
$js
</script></body></html>''';

String bstAnimation(String concept) => _doc(
      concept,
      'Inserting 50, 30, 70, 20, 40, 60, 80 — each key walks down one path',
      r'''
.node circle{fill:#1c1c1e;stroke:#3a3a3c;stroke-width:2;transition:all .35s cubic-bezier(.3,2,.5,1)}
.node text{fill:#f5f5f7;font-size:15px;font-weight:600;text-anchor:middle;dominant-baseline:central}
.node{opacity:0;transform-box:fill-box;transform-origin:center;transform:scale(.6);
transition:opacity .45s ease,transform .5s cubic-bezier(.3,2,.5,1)}
.node.on{opacity:1;transform:scale(1)}
.node.path circle{stroke:#5e7bff;fill:#1d2552}
.node.new circle{stroke:#30d158;fill:#0f3320}
line{stroke:#3a3a3c;stroke-width:2;opacity:0;transition:opacity .4s}
line.on{opacity:1}
''',
      '<svg viewBox="0 0 800 380" id="s"></svg>',
      r'''
const pos={50:[400,50],30:[220,150],70:[580,150],20:[130,260],40:[310,260],60:[490,260],80:[670,260]};
const parent={30:50,70:50,20:30,40:30,60:70,80:70};
const order=[50,30,70,20,40,60,80];
const s=document.getElementById('s');const ns='http://www.w3.org/2000/svg';
const nodes={},lines={};
for(const k of order){ if(parent[k]){const l=document.createElementNS(ns,'line');const[a,b]=pos[parent[k]],[c,d]=pos[k];
l.setAttribute('x1',a);l.setAttribute('y1',b);l.setAttribute('x2',c);l.setAttribute('y2',d);s.appendChild(l);lines[k]=l;} }
for(const k of order){const g=document.createElementNS(ns,'g');g.setAttribute('class','node');
const[x,y]=pos[k];g.innerHTML=`<circle cx="${x}" cy="${y}" r="26"/><text x="${x}" y="${y}">${k}</text>`;s.appendChild(g);nodes[k]=g;}
function pathTo(k){const p=[];let c=parent[k];while(c){p.unshift(c);c=parent[c];}return p;}
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function run(){
  if(reduce){for(const k of order){nodes[k].classList.add('on');lines[k]&&lines[k].classList.add('on');}return;}
  for(;;){
    for(const k of order){nodes[k].className.baseVal='node';lines[k]&&lines[k].classList.remove('on');}
    await wait(500);
    for(const k of order){
      for(const p of pathTo(k)){nodes[p].classList.add('path');await wait(380);nodes[p].classList.remove('path');}
      lines[k]&&lines[k].classList.add('on');nodes[k].classList.add('on','new');await wait(520);nodes[k].classList.remove('new');
    }
    await wait(2200);
  }
}
run();
''',
    );

String growthAnimation(String concept) => _doc(
      concept,
      'EGP 1,000 at 20% a year — simple interest vs compound interest',
      r'''
.chart{display:flex;align-items:flex-end;gap:1.6%;padding:4% 0 2%}
.col{flex:1;display:flex;gap:6%;align-items:flex-end;height:100%;position:relative}
.bar{flex:1;border-radius:6px 6px 2px 2px;height:0;transition:height .7s cubic-bezier(0,0,.5,1)}
.simple{background:#3a3a3c}.compound{background:linear-gradient(#5e7bff,#3b4fd8)}
.yr{position:absolute;bottom:-22px;left:0;right:0;text-align:center;color:#6e6e73;font-size:11px}
.legend{display:flex;gap:18px;font-size:12px;color:#a1a1a6;margin-top:28px}
.legend i{display:inline-block;width:10px;height:10px;border-radius:3px;margin-right:6px;vertical-align:-1px}
''',
      '<div><div class="chart" id="c" style="height:calc(100% - 50px)"></div>'
          '<div class="legend"><span><i class="simple"></i>Simple</span><span><i class="compound"></i>Compound</span></div></div>',
      r'''
const c=document.getElementById('c');const years=10,P=1000,r=.2;
const max=P*Math.pow(1+r,years);const cols=[];
for(let y=1;y<=years;y++){const col=document.createElement('div');col.className='col';
col.innerHTML=`<div class="bar simple"></div><div class="bar compound"></div><div class="yr">Y${y}</div>`;c.appendChild(col);cols.push(col);}
const wait=ms=>new Promise(res=>setTimeout(res,ms));
function set(y,on){const[s,k]=cols[y-1].querySelectorAll('.bar');
s.style.height=on?(P*(1+r*y)/max*100)+'%':'0';k.style.height=on?(P*Math.pow(1+r,y)/max*100)+'%':'0';}
async function run(){
  if(reduce){for(let y=1;y<=years;y++)set(y,true);return;}
  for(;;){for(let y=1;y<=years;y++)set(y,false);await wait(700);
    for(let y=1;y<=years;y++){set(y,true);await wait(380);}await wait(2600);}
}
run();
''',
    );

String keyPointsAnimation(String concept, List<(String, String)> points) {
  final items = points.take(4).map((p) =>
      '<li><b>${htmlEscape(p.$1)}</b><span>${htmlEscape(p.$2)}</span></li>').join();
  return _doc(
    concept,
    'The key ideas, step by step',
    r'''
ol{list-style:none;margin:0;padding:4% 0 0;counter-reset:k;display:grid;gap:14px;align-content:start}
li{counter-increment:k;display:grid;grid-template-columns:40px 1fr;column-gap:14px;opacity:0;
transform:translateY(24px);transition:transform .7s cubic-bezier(0,0,.5,1),opacity .9s ease}
li.on{opacity:1;transform:none}
li::before{content:counter(k);grid-row:span 2;width:40px;height:40px;border-radius:50%;display:grid;
place-items:center;background:#1d2552;color:#9fb0ff;font-weight:700}
li b{font-size:clamp(14px,2vw,18px)}li span{color:#a1a1a6;font-size:clamp(12px,1.6vw,15px)}
''',
    '<ol id="l">$items</ol>',
    r'''
const li=[...document.querySelectorAll('li')];const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function run(){
  if(reduce){li.forEach(l=>l.classList.add('on'));return;}
  for(;;){li.forEach(l=>l.classList.remove('on'));await wait(600);
    for(const l of li){l.classList.add('on');await wait(900);}await wait(3000);}
}
run();
''',
  );
}
