import 'package:flutter_test/flutter_test.dart';

import 'package:zakerly/core/animations.dart';
import 'package:zakerly/core/mock/mock_animations.dart';
import 'package:zakerly/core/preferences.dart';
import 'package:zakerly/core/prompts.dart';

void main() {
  group('matchAnimationTemplate', () {
    test('routes tree/BST concepts to the tree template', () {
      expect(matchAnimationTemplate('Binary search trees'), AnimationTemplate.tree);
      expect(matchAnimationTemplate('How does a BST insert work?'), AnimationTemplate.tree);
    });

    test('routes finance concepts to the growth template', () {
      expect(matchAnimationTemplate('Compound interest'), AnimationTemplate.growth);
      expect(matchAnimationTemplate('Simple vs compound investing'), AnimationTemplate.growth);
    });

    test('summary concepts fall back to key ideas, even for a course about trees', () {
      // Regression for the bug where a "tree" heading pulled in from the
      // course's retrieved chunks caused a plain summary concept to render
      // the BST animation instead of the generic key-ideas template.
      expect(matchAnimationTemplate('Summarize the key ideas'), AnimationTemplate.keyIdeas);
    });

    test('unknown concepts fall back to key ideas', () {
      expect(matchAnimationTemplate('Something entirely unrelated'), AnimationTemplate.keyIdeas);
    });
  });

  group('generated documents', () {
    void checkContract(String html) {
      expect(html, startsWith('<!doctype html>'));
      // The SVG namespace URI ('http://www.w3.org/2000/svg') is not a
      // network reference, so only forbid it in src/href/@import/url(...).
      final external = RegExp(
        r'''(?:src|href)\s*=\s*["']https?://|@import|url\(\s*["']?https?://''',
        caseSensitive: false,
      );
      expect(html, isNot(matches(external)), reason: 'must not reference any external URL');
      // Colours come from the app theme, not the OS setting.
      expect(html, isNot(contains('prefers-color-scheme')));
      expect(html, contains('prefers-reduced-motion'));
      expect(html, contains('id="back"'));
      expect(html, contains('id="play"'));
      expect(html, contains('id="next"'));
      expect(html, contains(AnimationMessages.next));
      expect(html, contains(AnimationMessages.escape));
      expect(html, contains('ArrowRight'));
      expect(html, contains('ArrowLeft'));
      expect(html, contains('html,body{margin:0;width:100%;height:100%'));
      expect(html.contains('\u2014') || html.contains('\u2013'), isFalse,
          reason: 'no em dash or en dash characters anywhere');
      expect(html, isNot(contains('Generated by Zakerly')));
    }

    test('bstAnimation follows the shared contract', () {
      final html = bstAnimation('Binary search trees');
      checkContract(html);
      expect(html, contains('<html lang="en" dir="ltr">'));
      expect(html, contains('Step {i} of {n}'));
      expect(html, contains(AnimationPalette.light.bg));
    });

    test('documents follow the app language and theme', () {
      final html = bstAnimation(
        'Binary search trees',
        language: AppLanguage.arabic,
        theme: AnimationTheme.dark,
      );
      checkContract(html);
      expect(html, contains('<html lang="ar" dir="rtl">'));
      final copy = AnimationCopy.of(AppLanguage.arabic);
      expect(html, contains('>${copy.back}</button>'));
      expect(html, contains('>${copy.next}</button>'));
      expect(html, contains(copy.stepTemplate));
      expect(html, isNot(contains('>Back<')));
      expect(html, contains(AnimationPalette.dark.bg));
      expect(html, isNot(contains(AnimationPalette.light.bg)));
    });

    test('growthAnimation follows the shared contract', () {
      checkContract(growthAnimation('Compound interest'));
    });

    test('keyPointsAnimation follows the shared contract, including the empty-points fallback', () {
      checkContract(keyPointsAnimation('Summarize the key ideas', const []));
      checkContract(keyPointsAnimation('Summarize the key ideas', const [
        ('Heading one', 'The first idea.'),
        ('Heading two', 'The second idea.'),
      ]));
    });

    test('keyPointsAnimation captions do not break out of the script tag', () {
      final html = keyPointsAnimation('Concept', const [
        ('</script><script>alert(1)</script>', 'text'),
      ]);
      expect(html, isNot(contains('</script><script>alert')));
    });
  });

  group('animation prompt', () {
    test('carries the app language and theme, and drops prefers-color-scheme', () {
      final system = Prompts.animationSystemFor(
        language: AppLanguage.arabic,
        theme: AnimationTheme.dark,
      );
      expect(system, contains('dir="rtl"'));
      expect(system, contains(AnimationPalette.dark.bg));
      expect(system, contains('do NOT use a prefers-color-scheme'));
      expect(system, contains(AnimationMessages.toggle));
      final prompt = Prompts.animation(
        'Trees',
        const [],
        language: AppLanguage.arabic,
        theme: AnimationTheme.dark,
      );
      expect(prompt, contains('LANGUAGE: ar'));
      expect(prompt, contains('THEME: dark'));
    });
  });
}
