import 'package:flutter_test/flutter_test.dart';

import 'package:zakerly/core/animations.dart';
import 'package:zakerly/core/mock/mock_animations.dart';

void main() {
  group('matchAnimationTemplate', () {
    test('routes tree/BST concepts to the tree template', () {
      expect(matchAnimationTemplate('Binary search trees'), AnimationTemplate.tree);
      expect(matchAnimationTemplate('How does a BST insert work?'), AnimationTemplate.tree);
    });

    test('routes finance concepts to the growth template', () {
      expect(matchAnimationTemplate('Compound interest'), AnimationTemplate.growth);
      expect(matchAnimationTemplate('Simple vs compound investing'), AnimationTemplate.growth);
    });

    test('summary concepts fall back to key ideas, even for a course about trees', () {
      // Regression for the bug where a "tree" heading pulled in from the
      // course's retrieved chunks caused a plain summary concept to render
      // the BST animation instead of the generic key-ideas template.
      expect(matchAnimationTemplate('Summarize the key ideas'), AnimationTemplate.keyIdeas);
    });

    test('unknown concepts fall back to key ideas', () {
      expect(matchAnimationTemplate('Something entirely unrelated'), AnimationTemplate.keyIdeas);
    });
  });

  group('generated documents', () {
    void checkContract(String html) {
      expect(html, startsWith('<!doctype html>'));
      // The SVG namespace URI ('http://www.w3.org/2000/svg') is not a
      // network reference, so only forbid it in src/href/@import/url(...).
      final external = RegExp(
        r'''(?:src|href)\s*=\s*["']https?://|@import|url\(\s*["']?https?://''',
        caseSensitive: false,
      );
      expect(html, isNot(matches(external)), reason: 'must not reference any external URL');
      expect(html, contains('prefers-color-scheme'));
      expect(html, contains('prefers-reduced-motion'));
      expect(html, contains('#4C63F5'));
      expect(html, contains('id="back"'));
      expect(html, contains('id="play"'));
      expect(html, contains('id="next"'));
      expect(html, contains("'Step '"));
      expect(html, contains('ArrowRight'));
      expect(html, contains('ArrowLeft'));
      expect(html, contains('html,body{margin:0;width:100%;height:100%'));
      expect(html.contains('—') || html.contains('–'), isFalse,
          reason: 'no em dash or en dash characters anywhere');
      expect(html, isNot(contains('Generated by Zakerly')));
    }

    test('bstAnimation follows the shared contract', () {
      checkContract(bstAnimation('Binary search trees'));
    });

    test('growthAnimation follows the shared contract', () {
      checkContract(growthAnimation('Compound interest'));
    });

    test('keyPointsAnimation follows the shared contract, including the empty-points fallback', () {
      checkContract(keyPointsAnimation('Summarize the key ideas', const []));
      checkContract(keyPointsAnimation('Summarize the key ideas', const [
        ('Heading one', 'The first idea.'),
        ('Heading two', 'The second idea.'),
      ]));
    });

    test('keyPointsAnimation captions do not break out of the script tag', () {
      final html = keyPointsAnimation('Concept', const [
        ('</script><script>alert(1)</script>', 'text'),
      ]);
      expect(html, isNot(contains('</script><script>alert')));
    });
  });
}
