import 'package:flutter_test/flutter_test.dart';

import 'package:zakerly/core/animations.dart';
import 'package:zakerly/core/mock/mock_animations.dart';
import 'package:zakerly/core/mock/mock_llm.dart';
import 'package:zakerly/core/models.dart';
import 'package:zakerly/core/preferences.dart';
import 'package:zakerly/core/prompts.dart';
import 'package:zakerly/core/retrieval.dart';
import 'package:zakerly/core/services.dart';

void main() {
  group('matchAnimationTemplate', () {
    test('routes tree/BST concepts to the tree template', () {
      expect(matchAnimationTemplate('Binary search trees'), AnimationTemplate.tree);
      expect(matchAnimationTemplate('How does a BST insert work?'), AnimationTemplate.tree);
    });

    test('routes finance concepts to the growth template', () {
      expect(matchAnimationTemplate('Compound interest'), AnimationTemplate.growth);
      expect(matchAnimationTemplate('Simple vs compound investing'), AnimationTemplate.growth);
    });

    test('summary concepts fall back to key ideas, even for a course about trees', () {
      // Regression for the bug where a "tree" heading pulled in from the
      // course's retrieved chunks caused a plain summary concept to render
      // the BST animation instead of the generic key-ideas template.
      expect(matchAnimationTemplate('Summarize the key ideas'), AnimationTemplate.keyIdeas);
    });

    test('unknown concepts fall back to key ideas', () {
      expect(matchAnimationTemplate('Something entirely unrelated'), AnimationTemplate.keyIdeas);
    });
  });

  group('generated documents', () {
    void checkContract(String html) {
      expect(html, startsWith('<!doctype html>'));
      // The SVG namespace URI ('http://www.w3.org/2000/svg') is not a
      // network reference, so only forbid it in src/href/@import/url(...).
      final external = RegExp(
        r'''(?:src|href)\s*=\s*["']https?://|@import|url\(\s*["']?https?://''',
        caseSensitive: false,
      );
      expect(html, isNot(matches(external)), reason: 'must not reference any external URL');
      // Colours come from the app theme, not the OS setting.
      expect(html, isNot(contains('prefers-color-scheme')));
      expect(html, contains('prefers-reduced-motion'));
      expect(html, contains('id="back"'));
      expect(html, contains('id="play"'));
      expect(html, contains('id="next"'));
      expect(html, contains(AnimationMessages.next));
      expect(html, contains(AnimationMessages.escape));
      expect(html, contains('ArrowRight'));
      expect(html, contains('ArrowLeft'));
      expect(html, contains('html,body{margin:0;width:100%;height:100%'));
      expect(html.contains('\u2014') || html.contains('\u2013'), isFalse,
          reason: 'no em dash or en dash characters anywhere');
      expect(html, isNot(contains('Generated by Zakerly')));
    }

    test('bstAnimation follows the shared contract', () {
      final html = bstAnimation('Binary search trees');
      checkContract(html);
      expect(html, contains('<html lang="en" dir="ltr">'));
      expect(html, contains('Step {i} of {n}'));
      expect(html, contains(AnimationPalette.light.bg));
    });

    test('documents follow the app language and theme', () {
      final html = bstAnimation(
        'Binary search trees',
        language: AppLanguage.arabic,
        theme: AnimationTheme.dark,
      );
      checkContract(html);
      expect(html, contains('<html lang="ar" dir="rtl">'));
      final copy = AnimationCopy.of(AppLanguage.arabic);
      expect(html, contains('>${copy.back}</button>'));
      expect(html, contains('>${copy.next}</button>'));
      expect(html, contains(copy.stepTemplate));
      expect(html, isNot(contains('>Back<')));
      expect(html, contains(AnimationPalette.dark.bg));
      expect(html, isNot(contains(AnimationPalette.light.bg)));
    });

    test('growthAnimation follows the shared contract', () {
      checkContract(growthAnimation('Compound interest'));
    });

    test('keyPointsAnimation follows the shared contract, including the empty-points fallback', () {
      checkContract(keyPointsAnimation('Summarize the key ideas', const []));
      checkContract(keyPointsAnimation('Summarize the key ideas', const [
        ('Heading one', 'The first idea.'),
        ('Heading two', 'The second idea.'),
      ]));
    });

    test('keyPointsAnimation captions do not break out of the script tag', () {
      final html = keyPointsAnimation('Concept', const [
        ('</script><script>alert(1)</script>', 'text'),
      ]);
      expect(html, isNot(contains('</script><script>alert')));
    });

    test('in-document controls and caption hide when hosted, and report each step', () {
      for (final html in [
        bstAnimation('Binary search trees'),
        growthAnimation('Compound interest'),
        keyPointsAnimation('Summarize', const [('A', 'a.'), ('B', 'b.'), ('C', 'c.')]),
      ]) {
        // Standalone: the controls exist and work (no data-hosted on <html>).
        expect(html, contains('class="controls"'));
        expect(html, isNot(contains('data-hosted lang')));
        expect(html, contains('html[data-hosted] .controls,html[data-hosted] .caption{display:none}'));
        expect(html, contains(AnimationMessages.stepPrefix));
        expect(html, contains('window.parent.postMessage'));

        final hosted = withHostedFlag(html);
        expect(hosted, contains('<html data-hosted lang="en" dir="ltr">'));
        expect(withHostedFlag(hosted), hosted, reason: 'idempotent');
      }
    });

    test('withHostedFlag handles documents without an <html> tag', () {
      expect(
        withHostedFlag('<!doctype html><body>x</body>'),
        '<!doctype html><html data-hosted><body>x</body>',
      );
      expect(withHostedFlag('<p>x</p>'), '<html data-hosted><p>x</p>');
      // <header> is not <html>.
      expect(withHostedFlag('<header>x</header>'), '<html data-hosted><header>x</header>');
    });

    test('step 1 is not an empty stage', () {
      final bst = bstAnimation('Binary search trees');
      expect(bst, isNot(contains('empty tree')));
      expect(bst, contains('order.slice(0, step + 1)'));
      // Entrance transitions are off for the first paint.
      expect(bst, contains('html.first *{transition:none!important}'));
      expect(bst, contains("classList.add('first')"));
    });

    test('key ideas put the title next to the number badge, body below', () {
      final html = keyPointsAnimation('Summarize', const [('A', 'a.')]);
      expect(html, contains('grid-template-areas:"num title" ". body"'));
      expect(html, contains('li::before{grid-area:num'));
      expect(html, contains('li b{grid-area:title'));
      expect(html, contains('li span{grid-area:body'));
      expect(html, contains('width:min(100%,62em)'));
    });
  });

  group('AnimationStep.parse', () {
    test('accepts exactly the fixed shape', () {
      final s = AnimationStep.parse('zakerly:step:{"step":2,"total":5,"caption":" Hi "}');
      expect(s, isNotNull);
      expect(s!.step, 2);
      expect(s.total, 5);
      expect(s.caption, 'Hi');
    });

    test('rejects anything else', () {
      for (final m in [
        'zakerly:next',
        'zakerly:step:',
        'zakerly:step:not json',
        'zakerly:step:[1,2]',
        'zakerly:step:{"step":0,"total":5,"caption":""}',
        'zakerly:step:{"step":6,"total":5,"caption":""}',
        'zakerly:step:{"step":1,"total":5}',
        'zakerly:step:{"step":1,"total":5,"caption":"x","href":"y"}',
        'zakerly:step:{"step":"1","total":5,"caption":"x"}',
      ]) {
        expect(AnimationStep.parse(m), isNull, reason: m);
      }
    });
  });

  group('summary requests', () {
    CourseFile file(String id, List<(String, String)> sections) => CourseFile(
          id: id,
          courseId: 'c',
          name: '$id.pdf',
          kind: 'pdf',
          sourceTokens: 1000,
        )..chunks = [
            for (final (h, t) in sections) Chunk(fileId: id, fileName: '$id.pdf', heading: h, text: t),
          ];

    final files = [
      file('week1', [
        ('Supply and demand', 'Prices rise when demand outruns supply. Markets then adjust.'),
        ('Elasticity', 'Elasticity measures how much demand reacts to price.'),
        ('Main idea of markets', 'Markets coordinate buyers and sellers.'),
      ]),
      file('week2', [
        ('Opportunity cost', 'Every choice gives up the next best option.'),
        ('Comparative advantage', 'Trade lets each side focus on what it does cheapest.'),
      ]),
    ];

    test('a broad concept gets the course overview, not one retrieved chunk', () {
      const concept = 'Sum up the main ideas';
      expect(isBroadRequest(concept), isTrue);
      final context = animationContext(concept, files);
      expect(context.length, inInclusiveRange(3, 5));
      expect(context.map((c) => c.heading), containsAll(['Supply and demand', 'Opportunity cost']));
      // A specific concept still uses plain retrieval.
      expect(animationContext('Elasticity', files).map((c) => c.heading), ['Elasticity']);
    });

    test('the mock draws at least three ideas for a summary request', () async {
      const concept = 'Sum up the main ideas';
      final res = await MockLlm().generate(LlmRequest(
        purpose: LlmPurpose.animation,
        system: Prompts.animationSystemFor(),
        prompt: Prompts.animation(concept, animationContext(concept, files)),
        maxOutputTokens: 6000,
      ));
      expect(matchAnimationTemplate(concept), AnimationTemplate.keyIdeas);
      final ideas = RegExp('<li>').allMatches(res.text).length;
      expect(ideas, inInclusiveRange(3, 5));
    });

    test('the mock tops up to three ideas even from a single section', () async {
      final one = [
        file('solo', [('Only section', 'First point here. Second point here. Third point here.')]),
      ];
      final res = await MockLlm().generate(LlmRequest(
        purpose: LlmPurpose.animation,
        system: Prompts.animationSystemFor(),
        prompt: Prompts.animation('Sum up the main ideas', overviewChunks(one)),
        maxOutputTokens: 6000,
      ));
      expect(RegExp('<li>').allMatches(res.text).length, 3);
    });
  });

  group('animation prompt', () {
    test('carries the app language and theme, and drops prefers-color-scheme', () {
      final system = Prompts.animationSystemFor(
        language: AppLanguage.arabic,
        theme: AnimationTheme.dark,
      );
      expect(system, contains('dir="rtl"'));
      expect(system, contains(AnimationPalette.dark.bg));
      expect(system, contains('do NOT use a prefers-color-scheme'));
      expect(system, contains(AnimationMessages.toggle));
      // Same hosted contract as the mock documents.
      expect(system, contains('html[data-hosted] .controls'));
      expect(system, contains('class="controls"'));
      expect(system, contains(AnimationMessages.stepPrefix));
      expect(system, contains('Step 1 must already show real content'));
      expect(system, contains('3 to 5 ideas'));
      final prompt = Prompts.animation(
        'Trees',
        const [],
        language: AppLanguage.arabic,
        theme: AnimationTheme.dark,
      );
      expect(prompt, contains('LANGUAGE: ar'));
      expect(prompt, contains('THEME: dark'));
    });
  });
}
